# Problem 1 

In [3]:
# 1 - numpy kütüphanesini import edin
import numpy as np
# 2 - 5 elemanlı bir numpy array oluşturun
yetgenPython = np.array([32,99,105,85,64])
print(yetgenPython)
# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.
yetgenPython2 = np.sort(yetgenPython)
print(yetgenPython2)

[ 32  99 105  85  64]
[ 32  64  85  99 105]


# Problem 2

In [29]:
# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.
sayilar = np.array([10,15,30,45,60])
print("sayılar arrayı: ", sayilar)

# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
sayilar2 = np.arange(5,16)
print("sayılar2 array: ", sayilar2, "\n")
# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.
sayi= np.arange(50,100,5)
print("sayı3 arrayı: ", sayi, "\n")

# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.
sayi2 = np.zeros(10)
print("sayi2 arrayı: ", sayi2, "\n")


# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.
sayi3 = np.ones(8)
print("sayi3 arrayı: ", sayi3 , "\n")
# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.
sayi4 = np.linspace(0,100,7)
print("sayi4 arrayı: ", sayi4, "\n")
# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.
sayi5 = np.random.randint(10,31, size=5)
print("sayi5: ", sayi5, "\n")

# 8- [-1 ile 1] arasında 10 adet sayı üretin.
randSayi = np.random.uniform(-1,1,size=10)
print("üretilen random sayılar: ", randSayi)

# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.
randSayi2 = np.random.randint(10,50, size=(3,5))
print("3*5 matris: ", randSayi2, "\n")
                              
# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?
print(randSayi2.sum(axis=0))
print(randSayi2.sum(axis=1))

# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?
print(randSayi2.max())
print(randSayi2.min())
print(randSayi2.mean())

# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?
print("12:",randSayi2.argmax())

# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.
randSayi3 = np.random.randint(10,20, size=9)
print("13.soru:", randSayi3[:])

# 14- Üretilen dizinin elemanlarını tersten yazdırın.
print("14: ", randSayi3[::-1])


# 15- Üretilen matrisin ilk satırını seçiniz.
print(randSayi2[0])

# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?
print(randSayi2)
print(randSayi2[1],[2])

# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.
print(randSayi2[:,1])

# 18- Üretilen matrisin her bir elemanının karesini alınız.
print(randSayi2**2)

# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.
randSayi4 = np.random.randint(-50,50, size=(9,9))
print(randSayi4[randSayi4 % 2 == 0 & (randSayi4 > 0)])

sayılar arrayı:  [10 15 30 45 60]
sayılar2 array:  [ 5  6  7  8  9 10 11 12 13 14 15] 

sayı3 arrayı:  [50 55 60 65 70 75 80 85 90 95] 

sayi2 arrayı:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 

sayi3 arrayı:  [1. 1. 1. 1. 1. 1. 1. 1.] 

sayi4 arrayı:  [  0.          16.66666667  33.33333333  50.          66.66666667
  83.33333333 100.        ] 

sayi5:  [12 18 21 13 10] 

üretilen random sayılar:  [-0.05681808  0.91188304  0.53136557  0.27146082 -0.44355477  0.47033967
 -0.62357955  0.25628743 -0.23050675 -0.07886593]
3*5 matris:  [[41 20 31 22 42]
 [11 27 38 47 13]
 [25 24 45 14 11]] 

[ 77  71 114  83  66]
[156 136 119]
47
11
27.4
12: 8
13.soru: [16 10 18 19 13 16 12 17 19]
14:  [19 17 12 16 13 19 18 10 16]
[41 20 31 22 42]
[[41 20 31 22 42]
 [11 27 38 47 13]
 [25 24 45 14 11]]
[11 27 38 47 13] [2]
[20 27 24]
[[1681  400  961  484 1764]
 [ 121  729 1444 2209  169]
 [ 625  576 2025  196  121]]
[-46 -46  38  10  40  24  48  -2  -2 -28 -40 -26  24 -46  42   8  24  -6
   0 -24 -36 -26  18  10  4