# Problem 1

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 23.1.2
[notice] To update, run: C:\Users\sabah\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [ ]:
# 1 - numpy kütüphanesini import edin
import numpy as np
# 2 - 0 ile 10 arasında 5 sayıdan oluşan matris üretin
matris = np.random.randint(0, 10, (5,))
# 3 - matris'in boyutunu öğrenin
boyut = matris.shape
# 4 - matris'i yeniden boyutlandırın
matris = matris.reshape((5, 1))
# 5 - matris'in boyut sayısını öğrenin
boyut_sayisi = matris.ndim

# Problem 2

In [2]:
import numpy as np
# 1 - 0 ile 10 arasında bulunan tek sayılardan oluşan matris üretin

matrix = np.array([i for i in range(1, 10, 2)]).reshape(5, -1)
print(matrix)
# 2 - Oluşturduğunuz matrisi parçalayın
part1 = matrix[:2, :]
part2 = matrix[2:, :]
print(part1)
print(part2)

# 3 - Parçalanmış matrisleri birleştirin
merged_matrix = np.concatenate((part1, part2), axis=0)
print(merged_matrix)


[[1]
 [3]
 [5]
 [7]
 [9]]
[[1]
 [3]]
[[5]
 [7]
 [9]]
[[1]
 [3]
 [5]
 [7]
 [9]]


# Problem 3

In [3]:
import numpy as np
# 1 - 5 ile 100 arasında ikişer ikişer atlayarak rastgele 10 sayıdan oluşan matris üretin
matris = np.random.randint(5, 101, size=(5, 2))
print(matris)

# 2 - matris'in özelliklerini inceleyin
print("Matrisin şekli:", matris.shape)
print("Boyut sayısı:", matris.ndim)
print("Matrisin boyutu:", matris.size)
print("Matrisin veri tipi:", matris.dtype)
print("Matristeki tüm elemanların toplamı:", np.sum(matris))
print("Matristeki minimum değer:", np.min(matris))
print("Matristeki maksimum değer:", np.max(matris))


[[100  75]
 [ 22  34]
 [ 44  47]
 [  7  44]
 [ 79  99]]
Matrisin şekli: (5, 2)
Boyut sayısı: 2
Matrisin boyutu: 10
Matrisin veri tipi: int32
Matristeki tüm elemanların toplamı: 551
Matristeki minimum değer: 7
Matristeki maksimum değer: 100
